[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
amm = "BMkaAz3d4xw8dCeST8j3DnmVHPFuEpMiZNbeSkhTYreE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/millie/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
