[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow = "2jbdPsrCHrdTABsqASFvbDYspq7ySN4q8AeJB2BBY6TU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/millie/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
